export const GET_SERVICE_REQUEST_BY_ID_FIELDS = [
  'r.id',
  'r.created_by',
  'r.start_add',
  'r.start_state',
  'r.start_city',
  'r.end_add',
  'r.end_state',
  'r.end_city',
  'r.start_date',
  'r.description',
  'r.end_date',
  'st.id',
  'st.name',
  'user.id',
  'user.last_name',
  'user.first_name',
];
