export enum TransactionEvent {
  'ESCROW' = 'ESCROW',
  'HOLD' = 'HOLD',
  'PAID_SERVICE_PROVIDER' = 'PAID_SERVICE_PROVIDER',
  'CLIENT_CANCEL_FEE_SP' = 'CLIENT_CANCEL_FEE_SP',
  'CLIENT_CANCEL_FEE_SYSTEM' = 'CLIENT_CANCEL_FEE_SYSTEM',
  'CLIENT_CANCEL' = 'CLIENT_CANCEL',
  'CLIENT_CANCEL_FEE' = 'CLIENT_CANCEL_FEE',
  'DISPUTE_REFUND_CLIENT' = 'DISPUTE_REFUND_CLIENT',
  'DISPUTE_PAID_SP' = 'DISPUTE_PAID_SP',
  'SP_CANCEL' = 'SP_CANCEL',
  'CLIENT_SERVICE_FEE' = 'CLIENT_SERVICE_FEE',
  'SP_SERVICE_FEE' = 'SP_SERVICE_FEE',
  'SYSTEM_SERVICE_FEE' = 'SYSTEM_SERVICE_FEE',
  'FUNDING' = 'FUNDING',
  'PENDING_FUNDING' = 'PENDING_FUNDING',
  'WITHDRAWAL' = 'WITHDRAWAL',
}

export enum TransactionType {
  'DEBIT' = 'DEBIT',
  'CREDIT' = 'CREDIT',
}
export enum TransactionWallet {
  'CLIENT' = 'CLIENT',
  'SP' = 'SP',
  'SYSTEM' = 'SYSTEM',
}

export enum TransactionStatus {
  'SETTLED' = 'SETTLED',
  'NOT_SETTLED' = 'NOT_SETTLED',
}
