export const PROPOSAL_QUEUE = 'PROPOSAL_QUEUE';
export const START_PROPOSAL_PROCESS = 'START_PROPOSAL_PROCESS';

export const PROPOSAL_FEILDS = [
  'p.id',
  'p.status',
  'p.created_at',
  'p.cancelled_by',
  'p.sp_service_fee',
  'p.client_service_fee',
  'p.sp_proposal_amount',

  'p.invite_date',
  'p.invite_accept_date',
  'p.invite_decline_date',
  'p.invite_decline_reason',
  'p.invite_cancel_date',
  'p.invite_cancel_reason',
  'p.cancel_date',
  'p.cancel_reason',
  'p.proposal_sent_date',
  'p.proposal_accept_date',

  'client_rating.id',
  'client_rating.star',
  'client_rating.review',
  'client_rating.created_at',

  'sp_rating.id',
  'sp_rating.star',
  'sp_rating.review',
  'sp_rating.created_at',

  'p.amount_paid_date',
  'p.dispute_date',
  'p.dispute_resolve_date',
  'p.dispute_resolver',
  'p.dispute_resolve_action',
  'p.dispute_resolve_reason',
  'p.dispute_reason',
  'p.dispute_status',
  'p.disputant',

  'p.job_complete_date',
  'p.job_complete_note',
  'p.job_complete_file_1',
  'p.job_complete_file_2',
  'p.job_complete_file_3',
  'p.job_complete_file_4',
  'p.job_complete_file_5',
  'p.job_complete_file_6',

  'sr.id',
  'sr.start_add',
  'sr.start_state',
  'sr.start_city',
  'sr.end_add',
  'sr.end_state',
  'sr.end_city',
  'sr.start_date',
  'sr.description',
  'sr.end_date',
  'st.id',
  'st.name',
  'user.id',
  'user.last_name',
  'user.first_name',
  'sp.id',
  'sp.last_name',
  'sp.first_name',
];
